### ISSUE TITLE
Where can I find the cookie value?

### ISSUE THREAD

**Issue by DiabloOficjalnie** [Merrick919/Instagram-posts-to-Discord#24]
This error pops up in the console, I saw your tutorial on how to fix it, however, I cannot find the cookie value.

```
FetchError: invalid json response body at https://www.instagram.com/accounts/login/?next=/xxx/ reason: Unexpected token < in JSON at position 0
    at /home/instaMiszel/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/instaMiszel/main.js:351:24) {
  type: 'invalid-json'

```

**Comment by MrFoxyOfficial** [comment]
![image](https://user-images.githubusercontent.com/1783339/199611516-bd2e7f40-c714-4d36-87ac-c6a47f321927.png)
